#:schema node_modules/wrangler/config-schema.json
name = "submama"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "e3d8ee2ac9e74404bdb477fef71ac9b6" }
]
